version: '3.1'
services:
  stats-server:
    build: ./stats-service/server
    image: stats-service
    container_name: stats-server

    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/

    container_name: stats-db

    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=mainservice
      - SPRING_DATASOURCE_PASSWORD=mainservice
      - STATS_SERVER_URL=http://server:9090

  main-db:
    image: postgres:14-alpine

    volumes:
      - /var/lib/postgresql/data/

    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=mainservice
      - POSTGRES_USER=mainservice
      - POSTGRES_DB=main-db