version: '3.1'
services:
  stats-server:
    build: ./stats-service/server
    image: stats-service
    container_name: server

    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/

    container_name: stats-db

    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
